version: '3'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
    - ./frontend:/myapp
    - /myapp/node_modules
    ports:
    - 80:3000
    depends_on:
    - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
    - ./backend:/myapp
    - /myapp/node_modules
    expose:
    - 3000:3000
    depends_on:
    - mongo
    restart: always
  
  mongo:
    image: mongo:latest
    expose:
    - 27017:27017
    volumes:
    - ./data:/data/db
    restart: always
  
